version: '3.8'

services:
  api-gateway:
    image: nginx:latest
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"  # Expose API Gateway on localhost:8080
    depends_on:
      - queue-service-1
      - queue-service-2
      - queue-service-3
    restart: always

  queue-service-1:
    build:
      context: ./queue-service-1
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    restart: always

  queue-service-2:
    build:
      context: ./queue-service-2
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    restart: always

  queue-service-3:
    build:
      context: ./queue-service-3
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Expose Redis for development if needed
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ message broker
      - "15672:15672"  # RabbitMQ management UI
    restart: always

networks:
  default:
    driver: bridge
